### ISSUE TITLE
CH simulator sometimes segment faults for circuit with u1 gate

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#99] opened 2019-03-22 14:34 UTC
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.6
- **Operating system**: MacOS 10.14.3

### What is the current behavior?

@padraic-padraic this may be related to issue #98, or something different. While trying to debug that issue with Sergey I found that the CH simulator will cause a segmentation fault sometimes for circuits for a test circuit with a `u1` gate in it.

### Steps to reproduce the problem

Run the following script, at a random point in the iteration loop it may crash with a segmentation fault (though not always).

```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute
from qiskit.providers.aer import QasmSimulator
import numpy as np

qr = QuantumRegister(2, 'qr')
cr = ClassicalRegister(2, 'cr')
circ = QuantumCircuit(qr, cr)
circ.h(qr[0])
circ.cx(qr[0], qr[1])
circ.u1(np.pi / 100, qr[0])
circ.measure(qr, cr)

for j in range(100):
    result = execute(circ, QasmSimulator(), backend_options={"method": "ch"}).result()
    print("Execution {}:".format(j), result.get_counts(circ))
```

It also returns the incorrect output (same as #98 )

### What is the expected behaviour?

The execution doesn't cause a segmentation fault.

### Suggested solutions

None yet.

**Comment by padraic-padraic** [comment] 2019-03-22 14:46
I'll run this example locally and see if I can reproduce the error, thanks.

**Comment by padraic-padraic** [comment] 2019-03-22 17:17
The bug seems to be due to the way I cache the `u1` gates in `CHSimulator::Runner`. The set of rotations was shared between threads but there was no barrier or single region around the calls to `find` and `insert` hence the stochastic segmentation fault.

It can be fixed by marking the rotations as `thread_local`. Both fixes will be pushed shortly for testing!

**Closed** 2019-03-22 18:36 UTC
Labels: bug
