### ISSUE TITLE
failed job does not raise or report error message. need ``job.error_message()``

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-aer#623] opened 2020-02-20 18:28 UTC
Running an invalid job does not raise an error. Instead the error appears when you try `job.result()` and it is some convoluted Marshmallow message about an invalid Result object. 

Try running a non-Clifford circuit with the stabilizer method.
```
job.status()
>> <JobStatus.ERROR: 'job incurred error'>

job.error_message()  # IBMQJob has this and it would be nice to have here too
>> 

job.result()
>> ModelValidationError: "{'results': {0: {'shots': ['Missing data for required field.'], 'data': ['Missing data for required field.']}}}"
```

Nothing to actually say what the error is.

**Comment by chriseclectic** [comment] 2020-03-08 17:31
I can't reproduce this with your example. If I run a non-clifford circuit the job will return a result which will raise the invalid gate exception when you try and access the results:

```python
from qiskit import *

qc = QuantumCircuit(2, 2)
qc.u1(0.1, 0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])

sim = Aer.get_backend('qasm_simulator')
opts = backend_options={'method': 'stabilizer'}
job = execute(qc, sim, backend_options=opts)
result = job.result()
```
Then calling `result.data(0)` raises

```
QiskitError: 'PARTIAL COMPLETED ,  ERROR: Circuit contains invalid instructions ( invalid gate instructions: {u1} for stabilizer method)'
```

As I mentioned in the other issue, the fact it says partial completed when there is only a single circuit that failed is a bug that needs to be fixed.

**Comment by atilag** [comment] 2020-03-11 21:07
That could have changed with recent `Aer` updates?
I'm closing this, @ajavadia please re-open it if you face this error again.

**Closed by atilag** 2020-03-11 21:07 UTC
Labels: bug
