### ISSUE TITLE
The new version is incompatible with experiments in textbook 

### ISSUE THREAD

**Issue by Kid-key** [Qiskit/qiskit-aer#1245] opened 2021-05-02 09:07 UTC
### Informations

- **Qiskit Aer version**: 0.8
- **Python version**: 3.7 and 3.8
- **Operating system**: Linux Ubuntu 16.04

### What is the current behavior?
Traceback (most recent call last):
  File "<ipython-input-5-06b09ff4dd69>", line 4, in <module>
    print('Expected value for rotation pi {}'.format(circuit.run([np.pi])[0]))
  File "<ipython-input-3-227abd703128>", line 31, in run
    result = job.result().get_counts(self._circuit)
  File "/opt/conda/lib/python3.8/site-packages/qiskit/result/result.py", line 263, in get_counts
    exp = self._get_experiment(key)
  File "/opt/conda/lib/python3.8/site-packages/qiskit/result/result.py", line 370, in _get_experiment
    raise QiskitError('Data for experiment "%s" could not be found.' %
QiskitError: 'Data for experiment "circuit-89" could not be found.'

### Steps to reproduce the problem
run file in 'content/ch-machine-learning/machine-learning-qiskit-pytorch.ipynb' provided by the qiskit community 

### What is the expected behavior?
Give the simulation results.

### Suggested solutions
qiskit 0.23 and 0.24 with Qiskit Aer version 0.7 works

**Comment by rafal-pracht** [comment] 2021-05-08 16:56
It works fine when I replace the "result = job.result().get_counts(self._circuit)" by "result = job.result().get_counts()" in definition of QuantumCircuit.
I will fix this.

**Comment by rafal-pracht** [comment] 2021-05-08 17:01
I've just created PR https://github.com/qiskit-community/qiskit-textbook/pull/1072

**Comment by chriseclectic** [comment] 2021-05-11 14:18
Closing as duplicate of the issue in the qiskit-textbook repo

**Closed by chriseclectic** 2021-05-11 14:18 UTC
Labels: bug
