### ISSUE TITLE
Aer pulse simulator doesn't produce correct results for Armonk device

### ISSUE THREAD

**Issue by tnguyen-ornl** [Qiskit/qiskit-aer#966] opened 2020-09-30 16:50 UTC
### Informations

- **Qiskit Aer version**: 0.6.1
- **Python version**: 3.7.4
- **Operating system**: MacOS

### What is the current behavior?
I set up a simulation using backend configuration and defaults of the `armonk` backend.
The pulse of the X gate didn't produce a correct response: only ~60% in the |1> state vs. ~100% as expected.

### Steps to reproduce the problem

Code snippet below (backend data was queried on 9/30/2020.)

```
import qiskit.pulse.library as library
from qiskit.providers.aer.pulse.system_models.hamiltonian_model import HamiltonianModel
from qiskit.providers.aer.pulse.system_models.pulse_system_model import PulseSystemModel
from qiskit.pulse import (Schedule, Play, ShiftPhase, SetPhase, Delay, Acquire, SamplePulse,
                          DriveChannel, ControlChannel, AcquireChannel, MemorySlot)
from qiskit.compiler import assemble
from qiskit.providers.aer.backends import PulseSimulator
import numpy as np
# Simulate Armonk backend with Qiskit AER
"""
Reference backend data: (9/30/2020)
'h_str': ['_SUM[i,0,0,wq{i}/2*(I{i}-Z{i})]',
   '_SUM[i,0,0,delta{i}/2*O{i}*O{i}]',
   '_SUM[i,0,0,-delta{i}/2*O{i}]',
   '_SUM[i,0,0,omegad{i}*X{i}||D{i}]'],
  'osc': {},
  'qub': {'0': 3},
  'vars': {'delta0': -2.1895185763064315,
   'omegad0': 0.03620995108379614,
   'wq0': 31.255356263726036}},
 'rep_times': [1000.0],
 'dt': 0.2222222222222222,
 'dtm': 0.2222222222222222,
 'qubit_freq_est': [4.974444447470232]
 {'name': 'x',
   'qubits': [0],
   'sequence': [{'name': 'parametric_pulse',
     't0': 0,
     'ch': 'd0',
     'pulse_shape': 'drag',
     'parameters': {'amp': (0.657857142719338+0j),
      'beta': -4.72912208204562,
      'duration': 640,
      'sigma': 160}}]}
"""
def system_model_1Q(delta0, omegad0, wq0, freq_est):
    """Constructs a standard model for a 1 qubit system (armonk).
    Hamiltonian:
        "_SUM[i,0,0,wq{i}/2*(I{i}-Z{i})]",
        "_SUM[i,0,0,delta{i}/2*O{i}*O{i}]",
        "_SUM[i,0,0,-delta{i}/2*O{i}]",
        "_SUM[i,0,0,omegad{i}*X{i}||D{i}]"
    Returns:
        PulseSystemModel: model for qubit system
    """
    hamiltonian = {}
    hamiltonian['h_str'] = ['_SUM[i,0,0,wq{i}/2*(I{i}-Z{i})]',
                            '_SUM[i,0,0,delta{i}/2*O{i}*O{i}]',
                            '_SUM[i,0,0,-delta{i}/2*O{i}]',
                            '_SUM[i,0,0,omegad{i}*X{i}||D{i}]']
    hamiltonian['vars'] = {'delta0': delta0, 'omegad0': omegad0, 'wq0': wq0}
    hamiltonian['qub'] = {'0': 3}
    ham_model = HamiltonianModel.from_dict(hamiltonian)
    u_channel_lo = []
    subsystem_list = [0]
    dt = 0.2222222222222222
    return PulseSystemModel(hamiltonian=ham_model,
                            u_channel_lo=u_channel_lo,
                            qubit_freq_est=[freq_est],
                            subsystem_list=subsystem_list,
                            dt=dt)
def x_gate_by_pulse_sched():
    # Drag pulse represents X gate
    #{'amp': (0.657857142719338+0j), 'beta': -4.72912208204562, 'duration': 640, 'sigma': 160}}]}
    amp = 0.657857142719338
    sigma = 160
    beta = -4.72912208204562
    duration = 640
    drag_pulse = library.drag(duration, amp, sigma, beta=beta)
    drive_pulse = SamplePulse(drag_pulse.samples)
    schedule = Schedule()
    schedule |= Play(drive_pulse, DriveChannel(0))
    schedule |= Acquire(duration, AcquireChannel(0), MemorySlot(0)) << schedule.duration
    return schedule
"""
Params:
'delta0': -2.1895185763064315,
'omegad0': 0.03620995108379614,
'wq0': 31.255356263726036
'qubit_freq_est': [4.974444447470232]
"""
delta0 = -2.1895185763064315
omegad0 = 0.03620995108379614
wq0 = 31.255356263726036
freq_est = 4.974444447470232
system_model = system_model_1Q(delta0, omegad0, wq0, freq_est)
schedule = x_gate_by_pulse_sched()
backend_sim = PulseSimulator()
# set up schedule and qobj
qobj = assemble([schedule],
                backend=backend_sim,
                meas_level=2,
                meas_return='single',
                meas_map=[[0]],
                memory_slots=1,
                shots=1024)
# set backend backend_options including initial state
y0 = np.array([1.0, 0.0, 0.0])
backend_options = {'seed' : 9000, 'initial_state' : y0}
# run simulation
result = backend_sim.run(qobj, system_model=system_model, backend_options=backend_options).result()
# Print results
print(result.to_dict())
```

### What is the expected behavior?

Could you please take a look to see whether the set-up was not as expected or it is a bug in the simulator?

### Suggested solutions

Nil

**Comment by DanPuzzuoli** [comment] 2020-10-02 17:03
The results of the simulation are consistent with the parameters, so I don't believe this is due to any bug with the simulator. We can see this by looking at the probabilities of each energy level of the final state (after running your code) via:

`np.abs(result.get_statevector(0))**2`

resulting in:

`array([3.78475641e-01, 6.21524358e-01, 8.16647096e-10])`

To see what to expect roughly, we can look at the analytic predictions of a rotating wave approximation (RWA). Based on the way the Hamiltonian is parameterized, the expected unitary (if we ignore the third level) is `expm(-1j * (A * omegad0 / 2) * X)`, with `A` the area under the pulse and `X` the pauli X operator.

We can approximate the probabilities of reading `0` or `1` at the end (with a 2 level approximation) as:

```
dt = 0.2222222222222222
amp = 0.657857142719338
sigma = 160
beta = -4.72912208204562
duration = 640
drag_pulse = library.drag(duration, amp, sigma, beta=beta)
drive_pulse = SamplePulse(drag_pulse.samples)

# compute pulse area
A = drive_pulse.samples.sum() * dt

# compute probabilities in 2 level approximation with RWA
print(np.abs(expm(-1j * A * omegad0 * X / 2) @ np.array([1., 0]))**2)
```

this prints:

`array([0.37842542, 0.62157458])`

which agrees with the simulator up to a few decimal places (a deviation "reasonably" attributable to the RWA).

So, I think that either there is an issue with the reported parameters, or the calibrated pulse being used doesn't correspond to the one from which the Hamiltonian parameters were generated.

**Comment by tnguyen-ornl** [comment] 2020-10-02 17:12
Thanks @DanPuzzuoli. I guess the question then is why we have this discrepancy. 

I have carefully checked the configuration and defaults data of the `armonk` device to make sure the Hamiltonian and the pulse of the X gate are correct. 

Do you have any insights/suggestions to make this simulation work using backend information?

**Comment by DanPuzzuoli** [comment] 2020-10-02 17:44
For a short term solution you could modify `omegad0` so that the given X-gate produces a proper pi pulse, though obviously that could have unintended consequences for other gates. (In any case, to do this, we need `A * omegad0 / 2` to equal `np.pi / 2`, so setting `omegad0 = np.pi / A` will make the X gate work. Running this myself results in state 0 going to state 1 with >99.9%.)

For a proper solution we'll need some information about backend reporting.  @zachschoenfeld33

**Comment by zachschoenfeld33** [comment] 2020-10-05 14:58
Yes we are aware of the issue and a fix has been prepared. Hopefully should be merged in soon

**Comment by zachschoenfeld33** [comment] 2020-10-05 15:06
Until then, you can multiply the drive strength by 2, that will fix it.

**Comment by tnguyen-ornl** [comment] 2020-10-05 23:57
Thanks @zachschoenfeld33!
Yes, I can confirm that multiplying the drive strength (`omegad`) by 2 brought the final count distribution to ~96% |1> state using the `X` cmd-def on the aer simulator.

However, a multiplying factor of 1.7 is more ideal for the simulator (almost perfect 100% |1> state).
@zachschoenfeld33 Do you have any insights? Also, just want to confirm that this same multiplying factor also applies to U channel drive strength, right?

**Comment by zachschoenfeld33** [comment] 2020-10-07 13:29
I think that's just due to calibration error from the backend (since `x` is based on backend calibrations)--it should be 2.

Why are there U channels? I thought you're on Armonk? But yes, it's the same drive strength used so you'd need to multiply by the same factor there.

**Comment by tnguyen-ornl** [comment] 2020-10-07 13:33
@zachschoenfeld33 Thank you for the information.

Regarding the U channels, I meant for other backends, e.g. rome/bogota, which also have this drive strength mismatches.

**Comment by zachschoenfeld33** [comment] 2020-10-07 15:27
Yes use the same factor. Hopefully this will get pushed onto our backends soon...

**Comment by vvilpas** [comment] 2021-01-12 13:23
@DanPuzzuoli @zachschoenfeld33 I guess this is already fixed in Terra. Can we close it?

**Comment by zachschoenfeld33** [comment] 2021-01-12 14:59
I believe so

**Comment by tnguyen-ornl** [comment] 2021-01-12 21:58
Hi @zachschoenfeld33 

I just tried the below with latest Qiskit (from master branch)

```
from qiskit import IBMQ, transpile, schedule
from qiskit.circuit import QuantumCircuit
from qiskit.providers.aer.pulse import PulseSystemModel
from qiskit.compiler import assemble
from qiskit.providers.aer import PulseSimulator

IBMQ.save_account('##REDACTED##', overwrite=True)
IBMQ.load_account()
provider = IBMQ.get_provider(hub='##REDACTED##', group='##REDACTED##', project='##REDACTED##')


backend_sim = PulseSimulator()
backend = provider.get_backend('ibmq_bogota') # 'ibmq_armonk' or 'ibmq_bogota'
backend_model = PulseSystemModel.from_backend(backend)
# Construct a circuit
qc = QuantumCircuit(1,1, name = "x gate")
qc.x(0)
qc.measure(range(1),range(1))
qc = transpile(qc, backend)
pulse_schedule = schedule(qc, backend)
print("Pulse Schedule:", pulse_schedule)
shots = 1024
pulse_schedule = assemble(pulse_schedule,
                    backend=backend_sim,
                    qubit_lo_freq=backend.defaults().qubit_freq_est, 
                    meas_level=2,
                    meas_return="single",
                    shots=shots)
sim_result = backend_sim.run(pulse_schedule, backend_model).result()
print("Result:", sim_result.get_counts())
```

While the result is okay for `ibmq_armonk`, I don't get the correct answer for `ibmq_bogota` (see the `provider.get_backend` line).
I always get all zeros when using `ibmq_bogota` backend.

Could you please confirm that it is indeed fixed for all pulse backends?

**Comment by zachschoenfeld33** [comment] 2021-01-13 18:56
It seems that the backend numbers may not be getting reported correctly, although this is not due to the simulator or prior backend issue. Check `backend.configuration().hamiltonian['vars']`. You will see that the delta's (anharmonicities) are all 0. I am currently inquiring. I can confirm that Rome, Athens and Casablanca all work

**Comment by zachschoenfeld33** [comment] 2021-01-15 17:27
I have confirmed that some of the backends were not receiving the correct numbers from our internal database. We are working on fixing it. @dtmcclure may be able to further comment

**Comment by dtmcclure** [comment] 2021-01-20 04:41
Sorry for the delay. I was fixing this over the last several days. I think they should all be good now, and we have a better system in place to make sure they don't get left empty in the future. Let me know if you see any still missing. Thanks for bringing it to our attention.

**Closed** 2021-01-20 20:16 UTC
Labels: bug
