### ISSUE TITLE
Tensor network simulator backend

### ISSUE THREAD

**Issue by yehuda-naveh** [Qiskit/qiskit-aer#56] opened 2019-02-12 23:45 UTC
### What is the expected enhancement?

This issue is to track development of the tensor network simulator (currently in MPS form). WIP PR will follow soon by @eladgoldman 

### Codebase

- [x] Fully interface with Qiskit - be a backend / provider

- [x] Implement all relevant base functions for simulator

- [x] Currently known bugs to fix: miscompares in special cases with Qasm simulator, some memory fails

- [x] Test suites

- [x] Runtime and memory performance profiling and optimizations

- [x] Documentation in code, readme, and tutorials/notebooks

- [x] Compilation files (make)

### Benchmarking

- [x] Random circuits (including T's), parametrized by number of number of qubits, depth, and percentage of CXs

- [ ] Structured circuits

- [ ] Relevant benchmarks from the test library https://github.com/Qiskit/qiskit/tree/master/test/benchmarks

- [ ] Aqua usecases

- [x] Find the qubit limit - currently we stopped at 23 for confidence reasons (needed to compare full statevectors to reference) but appears can go much higher when asking only for expectation values

### Enhancements

- [x] Native interface for input observable(s) to get their expectation value at output

- [ ] Native dealing with non-nearest-neighbors CX's (i.e., without hidden SWAPs). This is possible as long as no CX-cycles, so need to add SWAPs only when encountering cycles in input (today SWAPing on any non-nearest neighbor)

- [ ] Consider possibilities to use incrementally - taking advantage of previous results on sub-circuit

- [ ] Consider possibilities to parallelize (@hhorii we hope you could help here when the code matures)

**Comment by yehuda-naveh** [comment] 2019-02-12 23:50
Will add below some preliminary runtime results. All cases are random circuits with X,Y,Z,H,S,T,CX gates, CX percentage is 10%, all others are uniform. Time in all charts is in seconds. All datapoints are checked for correctness against the Aer Qasm simulator full statevector

**Comment by yehuda-naveh** [comment] 2019-02-12 23:56
Full calculation of statevector at end of TN run:

[TN vs. qasm benchmark_10.pdf](https://github.com/Qiskit/qiskit-aer/files/2858199/TN.vs.qasm.benchmark_10.pdf)

**Comment by yehuda-naveh** [comment] 2019-02-12 23:59
Without calculation of statevector at end of TN run (for use, e.g., for expectation value finding):

[TN vs. qasm benchmark_10_no_statevector_expansion.pdf](https://github.com/Qiskit/qiskit-aer/files/2858204/TN.vs.qasm.benchmark_10_no_statevector_expansion.pdf)

**Comment by yehuda-naveh** [comment] 2019-02-13 00:05
Calculating expectation value of X on a single qubit:

[TN vs. qasm benchmark_10_expectation_X.pdf](https://github.com/Qiskit/qiskit-aer/files/2858216/TN.vs.qasm.benchmark_10_expectation_X.pdf)

**Comment by merav-aharoni** [comment] 2019-02-25 11:14
Here is a graph of running the tensor network simulator up to 128 qubits (without calculating the statevector).  Qasm ran up to 26 qubits.
![image](https://user-images.githubusercontent.com/46567124/53333673-321ba800-38ff-11e9-905f-ce1108e93e69.png)

**Comment by eladgoldman** [comment] 2019-03-03 16:23
Here is a graph of a benchmark for calculating expectation value on subset of qubits.
The matrix M is a tensor product of 5 random paulis on a subset of 5 following qubits.
Each point in the graph is an average of results of 5 circuits.

[TN vs. qasm expectaition value of 5 qubits benchmark 10% CNOTS.pdf](https://github.com/Qiskit/qiskit-aer/files/2923320/TN.vs.qasm.expectaition.value.of.5.qubits.benchmark.10.CNOTS.pdf)

**Comment by yehuda-naveh** [comment] 2019-03-04 20:11
Continued chart from Elad - runtime for getting expectation value of random Paulis on five consecutive qubits, for random circuits of depth 120 and up to 150 qubits

![tn vs qasm expectaition value of 5 qubit benchmark 10 cnots depth 120](https://user-images.githubusercontent.com/24368542/53759764-c53d7a80-3ec9-11e9-9200-c42d4529c1d3.jpeg)

**Comment by yehuda-naveh** [comment] 2019-03-04 20:13
Runtime does increase substantially with depth. Will show rigorous results of that soon

**Comment by yehuda-naveh** [comment] 2019-03-04 20:16
@chriseclectic or @atilag , I don't think I have write permissions here, can you please assign @merav-aharoni for this Issue? She'll be responsible for checking the checkboxes above to make it aer-ready

**Comment by yehuda-naveh** [comment] 2019-03-04 20:16
(and of course do the work behind the checkboxes :-) )

**Comment by yehuda-naveh** [comment] 2019-03-04 20:18
with @eladgoldman

**Comment by eladgoldman** [comment] 2019-03-12 11:13
Here two graphs of a benchmark for calculating expectation value on subset of qubits.
First graph, for 16 qubits, changing depth (20:10:620):

![TN vs  qasm expectaition value of 5 qubit benchmark 10% CNOTS qubits 16 depth 20to620](https://user-images.githubusercontent.com/41862856/54195769-397aae00-44c8-11e9-88f0-4fe79b4029d2.jpeg)

Second graph, for depth 120, changing number of  qubits (10:5:700), Qasm is shown up to 23 qubits:

![TN vs  qasm expectaition value of 5 qubit benchmark 10% CNOTS qubits 10to700 depth 120](https://user-images.githubusercontent.com/41862856/54195796-4e574180-44c8-11e9-9f98-ca4e7e6d7224.jpeg)

**Comment by yehuda-naveh** [comment] 2019-03-12 11:51
At some stage we will start benchmarking also on structured problems, in particular Aqua. For now we are mainly focused on infrastructure items and consistency, correctness, and extent of the algorithm. Hence the random benchmarks which in a sense provide the most simplest and straightforward results to analyze

**Comment by merav-aharoni** [comment] 2019-05-02 18:01
Current status:
Tensor network simulator is implemented as a simulation method of qasm controller.
Supported  operations: gates, snapshots (statevector and expectation value pauli).
Next steps: 
Testing, benchmarking - @eladgoldman 
Complete missing interface functions, additional code improvements - Merav
Review - @chriseclectic , @atilag

**Comment by atilag** [comment] 2020-05-18 15:24
It's been a while since we update this issue. I guess it was intended to be used as a "meta" or "epic" issue to track MPS simulator progress. 
@yehuda-naveh Can we close this and create issues for each of the remaining tasks?

**Comment by merav-aharoni** [comment] 2020-05-18 18:30
@atilag , you can close this issue.

**Closed** 2020-05-19 18:12 UTC
