### ISSUE TITLE
 qiskit-aer installation is failing on alpine 

### ISSUE THREAD

**Issue by jitendrs** [Qiskit/qiskit-aer#489] opened 2019-12-10 12:33 UTC
Hey folks,
During my work for Cirq alpine docker image creation, I came across error while building  image. I am running docker file on MacOs Catalina with docker version: 2.1.4
It seems like some dependency broken for qiskit-aer for alpine. 
Any help is appreciated.

Library             Version
OS                    alpine:3.10
python             3.7.5
pip                    19.2.3
qiskit-aer         0.3.4
numpy             1.17.4
scipy                1.3.3

### Steps to reproduce the problem
Trying to run install command on  alpine os with docker file.
RUN apk add python3-dev \
        python3-tkinter \
    &&  python3 -m pip install --upgrade pip \
    &&  python3 -m pip install cython numpy scipy scikit-build qiskit-aer \

### What is the expected behavior?
It should be install successfully. 

```
Collecting qiskit-aer
  Downloading https://files.pythonhosted.org/packages/0b/4a/5cbe3ad58941408b51156d9793549f17aa91257fc20a4d76b6e5209dc86f/qiskit-aer-0.3.4.tar.gz (6.8MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-htnv_sep/qiskit-aer/setup.py'"'"'; __file__='"'"'/tmp/pip-install-htnv_sep/qiskit-aer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-htnv_sep/qiskit-aer/pip-egg-info
         cwd: /tmp/pip-install-htnv_sep/qiskit-aer/
    Complete output (145 lines):
    Collecting scikit-build
      Downloading https://files.pythonhosted.org/packages/8a/b5/c6ca60421991c22e69b9a950b0d046e06d714f79f7071946ab885c7115fb/scikit_build-0.10.0-py2.py3-none-any.whl (66kB)
    Collecting packaging
      Downloading https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
    Requirement already satisfied: setuptools>=28.0.0 in /usr/lib/python3.7/site-packages (from scikit-build) (41.2.0)
    Collecting wheel>=0.29.0
      Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
    Collecting six
      Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
    Collecting pyparsing>=2.0.2
      Downloading https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl (67kB)
    Installing collected packages: six, pyparsing, packaging, wheel, scikit-build
    Successfully installed packaging-19.2 pyparsing-2.4.5 scikit-build-0.10.0 six-1.13.0 wheel-0.33.6
    Searching for Cython
    Reading https://pypi.org/simple/Cython/
    Downloading https://files.pythonhosted.org/packages/9c/9b/706dac7338c2860cd063a28cdbf5e9670995eaea408abbf2e88ba070d90d/Cython-0.29.14.tar.gz#sha256=e4d6bb8703d0319eb04b7319b12ea41580df44fd84d83ccda13ea463c6801414
    Best match: Cython 0.29.14
    Processing Cython-0.29.14.tar.gz
    Writing /tmp/easy_install-27bmnzti/Cython-0.29.14/setup.cfg
    Running Cython-0.29.14/setup.py -q bdist_egg --dist-dir /tmp/easy_install-27bmnzti/Cython-0.29.14/egg-dist-tmp-4p_zye6n
    Compiling /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Compiler/FusedNode.py because it changed.
    Compiling /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Tempita/_tempita.py because it changed.
    [1/8] Cythonizing /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Compiler/FlowControl.py
    [2/8] Cythonizing /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Compiler/FusedNode.py
    [3/8] Cythonizing /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Compiler/Scanning.py
    [4/8] Cythonizing /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Compiler/Visitor.py
    [5/8] Cythonizing /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Plex/Actions.py
    [6/8] Cythonizing /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Plex/Scanners.py
    [7/8] Cythonizing /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Runtime/refnanny.pyx
    [8/8] Cythonizing /tmp/easy_install-27bmnzti/Cython-0.29.14/Cython/Tempita/_tempita.py
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    warning: no files found matching 'pyximport/README'
    creating /tmp/pip-install-htnv_sep/qiskit-aer/.eggs/Cython-0.29.14-py3.7-linux-x86_64.egg
    Extracting Cython-0.29.14-py3.7-linux-x86_64.egg to /tmp/pip-install-htnv_sep/qiskit-aer/.eggs
    
    Installed /tmp/pip-install-htnv_sep/qiskit-aer/.eggs/Cython-0.29.14-py3.7-linux-x86_64.egg
    Searching for cmake
    Reading https://pypi.org/simple/cmake/
    Downloading https://files.pythonhosted.org/packages/0a/f5/3212616a15b4112d7ad075a407f007eac2cac59292a9d973f2ee7e3c4068/cmake-3.13.2.post1.tar.gz#sha256=b45cc0f56f3f5705f4b4678ecf1f82e09c852c01cb3ffff43effdf8ffa323b1d
    Best match: cmake 3.13.2.post1
    Processing cmake-3.13.2.post1.tar.gz
    Writing /tmp/easy_install-pexxznv0/cmake-3.13.2.post1/setup.cfg
    Running cmake-3.13.2.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pexxznv0/cmake-3.13.2.post1/egg-dist-tmp-bhy8v2ht
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-pexxznv0/cmake-3.13.2.post1/setup.py", line 78, in <module>
      File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 425, in setup
        _parse_setuptools_arguments(kw)
      File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 212, in _parse_setuptools_arguments
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 212, in <listcomp>
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/usr/lib/python3.7/distutils/dist.py", line 858, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
        _Command.__init__(self, dist)
      File "/usr/lib/python3.7/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-htnv_sep/qiskit-aer/setup.py", line 59, in <module>
        zip_safe=False
      File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 456, in setup
        return upstream_setup(*args, **kw)
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-pexxznv0/cmake-3.13.2.post1/setup.py", line 78, in <module>
      File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 425, in setup
        _parse_setuptools_arguments(kw)
      File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 212, in _parse_setuptools_arguments
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/usr/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 212, in <listcomp>
        for cmd in [dist.get_command_obj(command) for command in dist.commands]:
      File "/usr/lib/python3.7/distutils/dist.py", line 858, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
        _Command.__init__(self, dist)
      File "/usr/lib/python3.7/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by schwarmco** [comment] 2020-01-08 13:29
Hi @jitendrs,

i've also tried to create an Alpine-based Dockerimage but wasn't successful. However, after reading a blogpost (https://pythonspeed.com/articles/base-image-python-docker-images/) i gave python:3.7-slim-buster a shot and i'm quite happy with it:

```Dockerfile
FROM python:3.7-slim-buster

# Install dependencies.
RUN apt update && apt install -q -y libopenblas-dev python3-dev
RUN pip install cmake scikit-build numpy cython pybind11

# Install Qiskit Aer.
RUN pip install qiskit-aer
```

**Comment by atilag** [comment] 2020-03-11 19:43
Closing this issue as latest versions of Qiskit-Aer don't link against libpython, so this should be enough for it to run Alpine and other Linux  distros.
Feel free to reopen de issue if the problem is not really solved.

**Closed by atilag** 2020-03-11 19:43 UTC
Labels: bug, help wanted
