### ISSUE TITLE
GPU simulator freezes for circuits including resets.

### ISSUE THREAD

**Issue by Sola85** [Qiskit/qiskit-aer#1725] opened 2023-02-16 13:10 UTC
### Informations

- **Qiskit Aer version**: 0.11.2 (qiskit-aer-gpu)
- **Python version**: 3.8.10
- **Operating system**: Ubuntu 20.04.5
- **GPU information**: CUDA 11.8, Driver version 520.61.05, NVIDIA RTX A6000
- **Qiskit version**: 0.41.0

```python
from qiskit import QuantumCircuit, Aer


simulator= Aer.get_backend('aer_simulator_statevector')
simulator.set_options(device='GPU')

qc = QuantumCircuit(2)
qc.rxx(0.3,0,1)
qc.reset(0)
qc.measure_all()


result = simulator.run(qc, shots=10).result()
print(result)
```

### What is the current behavior?

`simulator.run` hangs indefinitely. The correct result is only returned in each of the following cases:
- Removing the line `simulator.set_options(device='GPU')`, i.e. simulating using the CPU
- removing the reset `qc.reset(0)`
- setting `shots=1`

### Steps to reproduce the problem

Run the above code on a system with GPU.

### What is the expected behavior?

The simulation finishes and a result is printed.

**Comment by doichanj** [comment] 2023-02-21 03:54
I could not reproduce this issue on the latest Qiskit Aer (built from source)
Could you please try using the latest one on your environment and if this issue will not be reproduced we can close this issue.

**Comment by hhorii** [comment] 2023-02-24 04:30
I would like to close this. Please reopen this or create new issue if the same situation is happened.

**Closed by hhorii** 2023-02-24 04:30 UTC
Labels: bug
