### ISSUE TITLE
Aer doesn't support Parameter binding method in backend.run

### ISSUE THREAD

**Issue by yulunwang** [Qiskit/qiskit-aer#1340] opened 2021-09-09 13:55 UTC
### Informations

- **Qiskit Aer version**: 0.8.2
- **Python version**: 3.7.6
- **Operating system**: Linux

### What is the current behavior?

> The Aer backend doesn't support parameter binding when using:
> backend = Aer.get_backend('qasm_simulator')
> job = backend.run(qc,parameter_binds=[{theta:0}])

> QiskitError: 'Mismatch between run_config.parameter_binds and all circuit parameters. Parameter binds: [] Circuit parameters: [ParameterView([Parameter(θ)])]'

But BasicAer beckend can do the parameter binding. However, BasicAer doesn't support noise_model when doing Parameter binding:
 

> backend = BasicAer.get_backend('qasm_simulator')
> job = backend.run(transpile(qc, backend),parameter_binds=[{theta:0}],noise_model=noise_model)

I got warning: 

> UserWarning: Option noise_model is not used by this backend

### Steps to reproduce the problem

from qiskit.circuit import Parameter
theta = Parameter('θ')
n = 5
qc = QuantumCircuit(5, 1)
qc.rz(theta, range(5))
qc.measure(0, 0)
qc.draw('mpl')

backend = Aer.get_backend('qasm_simulator')
job = backend.run(transpile(qc, backend),parameter_binds=[{theta:0}])
counts = job.result().get_counts()

### What is the expected behavior?

I think Qiskit is depreciating BasicAer and shifting to Aer. Aer should support parameter binding and noise  model at the same time.

**Comment by chriseclectic** [comment] 2021-09-13 15:16
Duplicate of #1249. This is supported in master as of #1317 and will be in the next stable release.

**Closed by chriseclectic** 2021-09-13 15:16 UTC
Labels: bug
