### ISSUE TITLE
Recursion error when pickling/unpickling Aer functions

### ISSUE THREAD

**Issue by kessler-frost** [Qiskit/qiskit-aer#1537] opened 2022-06-13 12:47 UTC
### What is the expected behavior?

Currently, if we try to pickle a qiskit function with `cloudpickle` we get the following error. The expected behavior is that it doesn't give this error:

```python
from qiskit import Aer
from qiskit.algorithms import QAOA
import cloudpickle as pickle


def get_qaoa(optimizer):
    return QAOA(optimizer, quantum_instance=Aer.get_backend('statevector_simulator'))


pickled_get_qaoa = pickle.dumps(get_qaoa)
pickle.loads(pickled_get_qaoa)
```

Error:

```python
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
/Users/sankalpsanand/dev/covalent/covalent/scratch.ipynb Cell 1' in <cell line: 11>()
           return QAOA(optimizer, quantum_instance=Aer.get_backend('statevector_simulator'))
      pickled_get_qaoa = pickle.dumps(get_qaoa)
--->  pickle.loads(pickled_get_qaoa)

File ~/opt/anaconda3/envs/cova-qa-1/lib/python3.8/site-packages/qiskit/__init__.py:89, in AerWrapper.__getattr__(self, attr)
      def __getattr__(self, attr):
--->      if not self.aer:
              try:
                  from qiskit.providers import aer

File ~/opt/anaconda3/envs/cova-qa-1/lib/python3.8/site-packages/qiskit/__init__.py:89, in AerWrapper.__getattr__(self, attr)
      def __getattr__(self, attr):
--->      if not self.aer:
              try:
                  from qiskit.providers import aer

    [... skipping similar frames: AerWrapper.__getattr__ at line 89 (2969 times)]

File ~/opt/anaconda3/envs/cova-qa-1/lib/python3.8/site-packages/qiskit/__init__.py:89, in AerWrapper.__getattr__(self, attr)
      def __getattr__(self, attr):
--->      if not self.aer:
              try:
                  from qiskit.providers import aer

RecursionError: maximum recursion depth exceeded
```
I think making these functions `cloudpickle`-able is a nice to have feature for remote execution.

**Comment by mtreinish** [comment] 2022-06-13 16:18
The issue you're hitting isn't actually an issue in Aer, it's in your reproduce code. The infinite recursion is because you're trying to serialize the lazy loader class directly by embedding `qiskit.Aer` inside a function. That class (which is part of `qiskit-terra` not `qiskit-aer`) isn't serializable by design. It's intended to be nothing but a compatibility shim that lazy loads aer to ensure an earlier API is respected without force aer to imported by terra on loading. To fix this you would need to change `Aer.get_backend('statevector_simulator'))` to `qiskit.providers.aer.backends.StatevectorSimulator()`. In other words running:

```python

from qiskit.providers.aer import backends
from qiskit.algorithms import QAOA
import pickle


def get_qaoa(optimizer):
    return QAOA(optimizer, quantum_instance=backends.StatevectorSimulator())


pickled_get_qaoa = pickle.dumps(get_qaoa)
pickle.loads(pickled_get_qaoa)
```
works locally for me.

That being said do note that backend objects are generally not serializeable as they often contain things like async execution handles or other objects which can't be serialized. Aer works because we have wrappers around the compiled extensions that can handle this for us.

I'm going to close this issue as I don't think there is anything else to do here. But please feel free to reopen it if I'm missing something or there is more to discuss on this.

**Closed by mtreinish** 2022-06-13 16:18 UTC
Labels: enhancement
