### ISSUE TITLE
Aer not getting imported.

### ISSUE THREAD

**Issue by satyardn** [Qiskit/qiskit-aer#2060] opened 2024-02-16 17:09 UTC
### Informations

- **Qiskit Aer version**: 0.13.3
- **Python version**: 3.10.12
- **Operating system**: Google Colab

### What is the current behavior?
I am currently practicing the codes using Google Colab. It was working perfect till 13th of February and now it's throwing error even if I have installed the Aer package separately. Installed Qiskit and Aer as well but when importing Aer, it throws below error:

ImportError: cannot import name 'Aer' from 'qiskit' (/usr/local/lib/python3.10/dist-packages/qiskit/__init__.py)

<img width="701" alt="image" src="https://github.com/Qiskit/qiskit-aer/assets/22808995/fbb7f65b-c630-46b5-ae8b-983385e610a5">

### Steps to reproduce the problem

Open Google Colab
Install below libraries: 
!pip install qiskit
!pip install qiskit-aer

Then import Aer:
from qiskit import Aer

### What is the expected behavior?
This should run without any error.

### Suggested solutions
None

**Comment by jakelishman** [comment] 2024-02-16 17:13
Thank you for the report.  This is expected behaviour of Qiskit 1.0 and noted in its release notes and deprecated in Qiskit 0.46 (our suggested upgrade path is to first upgrade to Qiskit 0.46, see the warnings that appear there so they can be fixed before finalising the upgrade to Qiskit 1.0).

The drop-in replacement for `qiskit.Aer` is `qiskit_aer.Aer`.

**Comment by jakelishman** [comment] 2024-02-18 18:25
I'll close this issue as "won't fix" now (because it's expected), but if you have other problems using Aer with Qiskit 1.0, please feel free to open more reports.

**Closed by jakelishman** 2024-02-18 18:25 UTC
Labels: bug
