### ISSUE TITLE
Parallelisation over experiments stops working after submitting unparallelised experiment

### ISSUE THREAD

**Issue by LSticher** [Qiskit/qiskit-aer#1873] opened 2023-07-12 14:33 UTC
### Informations

- **Qiskit Aer version**: 0.12.1
- **Python version**: 3.8.17
- **Operating system**: Ubuntu 22.04.2
- **CPU**: AMD Ryzen 5600x 6C/12T

### What is the current behavior?

I am trying to parallelise the execution of simultaneously submitted circuits, that is focusing on parallelisation set by the ```max_parallel_experiments``` option. I've run into two issues. The first issue is that the execution is not parallelised when a low, but still parallelisable, number of experiments is submitted. As example I've once submitted 6 circuits simultaneously and a second time I've submitted 12 circuits simultaneously. The 6 circuit experiment is not parallelised at all and is even slower to execute than the 12 circuit experiment.  

```python
import time
import qiskit
import qiskit_aer as qk_aer

serial_sim = qk_aer.AerSimulator(max_parallel_threads=1, max_parallel_experiments=1, max_parallel_shots=1)
parallel_sim = qk_aer.AerSimulator(max_parallel_threads=0, max_parallel_experiments=0, max_parallel_shots=0)

def get_circ():
    circ = qiskit.transpile(qiskit.circuit.library.QuantumVolume(num_qubits=20, depth=5), basis_gates=['u','cx'])
    circ.measure_all()
    return circ

circs6 = [get_circ() for i in range(6)]
circs12 = [get_circ() for i in range(12)]

t1 = time.time()
t = serial_sim.run(circs12).result()
t2 = time.time()
print(t2-t1)

t1 = time.time()
t = serial_sim.run(circs6).result()
t2 = time.time()
print(t2-t1)

t1 = time.time()
t = parallel_sim.run(circs12).result()
t2 = time.time()
print(t2-t1)

t1 = time.time()
t = parallel_sim.run(circs6).result()
t2 = time.time()
print(t2-t1)
```

On my machine this prints:

```python
2.516629219055176
1.2833096981048584
0.5285968780517578
1.3140149116516113
```
This should exemplify the non-parallelisation of the 6 circuit execution. While a bit weird, this is not my main problem. I assume there is some internal logic to decide when parallelisation is worth it/should actually be applied and the 6 circuit execution is (somewhat erroneously in this case) considered to be not worth parallelising.

However, my main problem is best exemplified by running the code below:

```python
import time
import qiskit
import qiskit_aer as qk_aer

parallel_sim = qk_aer.AerSimulator(max_parallel_threads=0, max_parallel_experiments=0, max_parallel_shots=0)

def get_circ():
    circ = qiskit.transpile(qiskit.circuit.library.QuantumVolume(num_qubits=20, depth=5), basis_gates=['u','cx'])
    circ.measure_all()
    return circ

circs6 = [get_circ() for i in range(6)]
circs12 = [get_circ() for i in range(12)]
circs12_2 = [get_circ() for i in range(12)]
circs12_3 = [get_circ() for i in range(12)]

t1 = time.time()
t = parallel_sim.run(circs12).result()
t2 = time.time()
print(t2-t1)

t1 = time.time()
t = parallel_sim.run(circs12_2).result()
t2 = time.time()
print(t2-t1)

t1 = time.time()
t = parallel_sim.run(circs6).result()
t2 = time.time()
print(t2-t1)

t1 = time.time()
t = parallel_sim.run(circs12).result()
t2 = time.time()
print(t2-t1)

t1 = time.time()
t = parallel_sim.run(circs12_2).result()
t2 = time.time()
print(t2-t1)

t1 = time.time()
t = parallel_sim.run(circs12_3).result()
t2 = time.time()
print(t2-t1)
``` 

On my machine this prints:
```python
0.5491137504577637
0.5917024612426758
1.1917970180511475
2.350322723388672
2.377985954284668
2.3746438026428223
```

That is, the first two 12 circuit executions run parallelised. The 6 circuit execution runs unparallelised as explained above. However, any following 12 circuit execution is no longer parallelised.

Interleaving an unparallelised circuit execution seems to prevent any further parallelisation, even if parallelisation would usually be applied in the absence of this interleaved execution.

Running the code above with the 6 circuit execution commented out instead returns:
```python
0.5457553863525391
0.5751059055328369
0.5115034580230713
0.5186796188354492
0.5156040191650391
```
That is, all runs are now parallelised.

### Steps to reproduce the problem

Running the above code snippets.

### What is the expected behavior?

Firstly, I would expect the 6 circuit execution to be parallelised.

Secondly, interleaving an unparallelised circuit execution should not break parallelisation for any further circuit execution.

### Suggested solutions

N.A.

**Comment by doichanj** [comment] 2023-07-26 01:54
This issue is caused by setting OpenMP nested parallel when number of parallel experiments is less than max number of existing threads.
To avoid this issue until this will be fixed, please set the number of circuits to `OMP_NUM_THREADS` 

https://github.com/Qiskit/qiskit-aer/blob/b4e393c57a946a5f003f9065c7887d1c4ff6f2dd/src/controllers/aer_controller.hpp#L959-L962

By the way OMP nested parallelism is not actually used currently. I will fix OpenMP parameters to get better speed up.

**Closed** 2023-09-15 08:30 UTC
Labels: bug
