### ISSUE TITLE
Some typos in qiskit_aer.AerSimulator docs

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-aer#1611] opened 2022-10-04 11:52 UTC
In https://qiskit.org/documentation/stubs/qiskit_aer.AerSimulator.html, there is a wild `~`:
<img width="630" alt="Screenshot 2022-10-04 at 13 49 10" src="https://user-images.githubusercontent.com/766693/193812136-dd8ce428-68b0-43c0-84c0-47dd6acf4f3a.png">

And a missing `<p>`:
<img width="648" alt="Screenshot 2022-10-04 at 13 49 36" src="https://user-images.githubusercontent.com/766693/193812194-b3d9f7ab-e352-46db-9baa-4db8a07df476.png">

**Comment by 1ucian0** [comment] 2022-10-04 11:58
There are also some missing options, like `accept_distributed_results`

**Comment by 2003jblake** [comment] 2023-01-19 23:25
Can I be assigned this please?
Ive sorted the rogue ~
I found a missing fullstop

Im not finding where the missing <p> belongs, I see no reason there isnt a break when compared to the other parts of the code

Is there anyone that can help me find the definitions of the missing methods and help me idenify which need definitions, as I see mps_omp_threads does not have documentation but is in the method list. No worries if I do not know enough and cant assign or help me

**Comment by hhorii** [comment] 2023-05-10 06:29
@2003jblake We are always welcome for anyone to send PRs.

**Comment by devilkiller-ag** [comment] 2023-05-26 10:00
Can I work on this issue?

**Comment by natestemen** [comment] 2023-06-08 22:46
@hhorii it looks like a PR has been accepted here, but it's not clear who should be awarded the bounty. Is this issue now complete?

Also, remember to assign the hackers who should receive the bounty to the issue so they can be awarded properly!

**Comment by hhorii** [comment] 2023-06-14 03:58
Hmmm, maybe due to configuration of this repository or organization, I cannot assign contributors to this issue. I would like to assign @Innanov and @TerraVenil to this.

**Comment by natestemen** [comment] 2023-06-14 04:58
@hhorii it looks like @1ucian0 was able to assign the hacker in https://github.com/Qiskit/qiskit-aer/issues/1632, so maybe he has admin privileges which allow him to do this?

**Comment by 1ucian0** [comment] 2023-06-14 12:59
hi @Innanov, can you comment on this issue so I can assign you?

**Comment by Innanov** [comment] 2023-06-14 13:38
yes, please, thank you

**Comment by natestemen** [comment] 2023-06-14 15:17
Should this issue be closed now? Our system does not recognize the bounty as complete since the issue is still open.

**Closed** 2023-06-20 21:26 UTC
Labels: good first issue, documentation
