### ISSUE TITLE
Open Pulse with Valencia fake device 

### ISSUE THREAD

**Issue by alejomonbar** [Qiskit/qiskit-aer#1047] opened 2020-11-17 17:54 UTC
### Informations

- **Qiskit Aer version**: 0.7.1
- **Python version**: 3.8.3
- **Operating system**: macOS

### What is the current behavior?

When I try to use [this model](https://qiskit.org/documentation/tutorials/circuits_advanced/11_pulse_simulator_duffing_model.html) to work with the Fake Valencia device I got the following error (see below)

<img width="543" alt="Screen Shot 2020-11-17 at 11 09 04 AM" src="https://user-images.githubusercontent.com/11268357/99423778-e7aa3e00-28ce-11eb-8d14-9f4608f736ff.png">

### Steps to reproduce the problem

```Python
import numpy as np

import qiskit.pulse as pulse
from qiskit.pulse.pulse_lib import GaussianSquare
from qiskit.compiler import assemble

from qiskit.ignis.characterization.calibrations import rabi_schedules

# The pulse simulator
from qiskit.providers.aer import PulseSimulator

# function for constructing duffing models
from qiskit.test.mock import FakeValencia
from qiskit.providers.aer.pulse import PulseSystemModel


# list of qubits to be used throughout the notebook
qubits = [0, 1, 2, 3, 4]

# Construct a measurement schedule and add it to an InstructionScheduleMap
meas_amp = 0.025
meas_samples = 1200
meas_sigma = 4
meas_width = 1150
meas_pulse = GaussianSquare(duration=meas_samples, amp=meas_amp,
                            sigma=meas_sigma, width=meas_width)

acq_sched = pulse.Acquire(meas_samples, pulse.AcquireChannel(0), pulse.MemorySlot(0))
acq_sched += pulse.Acquire(meas_samples, pulse.AcquireChannel(1), pulse.MemorySlot(1))
acq_sched += pulse.Acquire(meas_samples, pulse.AcquireChannel(2), pulse.MemorySlot(2))
acq_sched += pulse.Acquire(meas_samples, pulse.AcquireChannel(3), pulse.MemorySlot(3))
acq_sched += pulse.Acquire(meas_samples, pulse.AcquireChannel(4), pulse.MemorySlot(4))

measure_sched = pulse.Play(meas_pulse, pulse.MeasureChannel(0)) | pulse.Play(meas_pulse, pulse.MeasureChannel(1)) | pulse.Play(meas_pulse, pulse.MeasureChannel(2)) | pulse.Play(meas_pulse, pulse.MeasureChannel(3)) | pulse.Play(meas_pulse, pulse.MeasureChannel(4)) | acq_sched

inst_map = pulse.InstructionScheduleMap()
inst_map.add('measure', qubits, measure_sched)

# construct Rabi experiments
drive_amps = np.linspace(0, 0.9, 20)
drive_sigma = 16
drive_duration = 128
drive_channels = [pulse.DriveChannel(0), pulse.DriveChannel(1), pulse.DriveChannel(2), pulse.DriveChannel(3), pulse.DriveChannel(4)]

backend_sim = PulseSimulator()

backend = FakeValencia()

rabi_experiments, rabi_amps = rabi_schedules(amp_list=drive_amps,
                                             qubits=qubits,
                                             pulse_width=drive_duration,
                                             pulse_sigma=drive_sigma,
                                             drives=drive_channels,
                                             inst_map=backend.defaults().instruction_schedule_map,
                                             meas_map=backend.configuration().meas_map)

# instantiate the pulse simulator

valencia_model = PulseSystemModel.from_backend(backend)
f = backend.properties().frequency
freq = [f(0), f(1), f(2), f(3), f(4)]
# compute frequencies from the Hamiltonian
# qubit_lo_freq = two_qubit_model.hamiltonian.get_qubit_lo_from_drift()


rabi_qobj = assemble(rabi_experiments,
                      backend=backend_sim,
                      meas_level=1,
                      meas_return='avg',
                      shots=512)

# # run the simulation
rabi_result = backend_sim.run(rabi_qobj, valencia_model).result()
```

### What is the expected behavior?
Get the results for the simulation on a fake quantum Valencia.

**Comment by vvilpas** [comment] 2020-11-18 11:31
@alejomonbar thanks for reporting this! 
The problem is that when `valencia_model` is instantiated, some `UchannelLO` objects are created, but instead of having `scale` property as a complex number they end up with a `list`.
While we fix this, you can manually handle this doing the following right after `valencia_model` is created:
```
for uclo in valencia_model.u_channel_lo: 
    uclo[0].scale = complex(*uclo[0].scale)
```

**Comment by vvilpas** [comment] 2020-12-04 07:55
Closing as https://github.com/Qiskit/qiskit-terra/pull/5410 has been merged into master.

**Closed by vvilpas** 2020-12-04 07:55 UTC
Labels: bug
