### ISSUE TITLE
setup.py installs src directory, pyproject.toml file, and also cmake directory into a wrong location

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-aer#1574] opened 2022-08-08 23:01 UTC
### Informations

- **Qiskit Aer version**: 0.10.4
- **Python version**: 3.9
- **Operating system**: FreeBSD 13.1

### What is the current behavior?
In addition to python files, ```setup.py install``` Installs these files in ```$PREFIX```:
```
CMakeLists.txt
MANIFEST.in
README.md
cmake/FindPybind11.cmake
cmake/FindPythonExtensions.cmake
cmake/Linter.cmake
cmake/compiler_utils.cmake
cmake/conan.cmake
cmake/conan_utils.cmake
cmake/dependency_utils.cmake
cmake/findBLASInSpecificPath.cmake
cmake/nvcc_add_compiler_options.cmake
cmake/targetLinkLibrariesWithDynamicLookup.cmake
contrib/standalone/qasm_simulator.cpp
contrib/standalone/version.hpp
contrib/standalone/version.hpp.in
pyproject.toml
qiskit/__init__.pxd
src/controllers/aer_controller.hpp
src/controllers/controller_execute.hpp
src/framework/avx2_detect.hpp
src/framework/blas_protos.hpp
src/framework/circuit.hpp
src/framework/creg.hpp
src/framework/json.hpp
src/framework/json_parser.hpp
src/framework/linalg/almost_equal.hpp
src/framework/linalg/eigensystem.hpp
src/framework/linalg/enable_if_numeric.hpp
src/framework/linalg/linalg.hpp
src/framework/linalg/linops/linops_aer_vector.hpp
src/framework/linalg/linops/linops_array.hpp
src/framework/linalg/linops/linops_generic.hpp
src/framework/linalg/linops/linops_json.hpp
src/framework/linalg/linops/linops_map.hpp
src/framework/linalg/linops/linops_matrix.hpp
src/framework/linalg/linops/linops_unordered_map.hpp
src/framework/linalg/linops/linops_vector.hpp
src/framework/linalg/matrix_utils.hpp
src/framework/linalg/matrix_utils/matrix_defs.hpp
src/framework/linalg/matrix_utils/smatrix_defs.hpp
src/framework/linalg/matrix_utils/vmatrix_defs.hpp
src/framework/linalg/square.hpp
src/framework/linalg/vector.hpp
src/framework/linalg/vector_json.hpp
src/framework/matrix.hpp
src/framework/noise_utils.hpp
src/framework/operations.hpp
src/framework/opset.hpp
src/framework/pybind_basics.hpp
src/framework/pybind_casts.hpp
src/framework/pybind_json.hpp
src/framework/python_parser.hpp
src/framework/qobj.hpp
src/framework/results/data/data.hpp
src/framework/results/data/metadata.hpp
src/framework/results/data/mixins/data_cdict.hpp
src/framework/results/data/mixins/data_cmatrix.hpp
src/framework/results/data/mixins/data_creg.hpp
src/framework/results/data/mixins/data_cvector.hpp
src/framework/results/data/mixins/data_json.hpp
src/framework/results/data/mixins/data_mps.hpp
src/framework/results/data/mixins/data_rdict.hpp
src/framework/results/data/mixins/data_rvalue.hpp
src/framework/results/data/mixins/data_rvector.hpp
src/framework/results/data/mixins/pybind_data_cdict.hpp
src/framework/results/data/mixins/pybind_data_cmatrix.hpp
src/framework/results/data/mixins/pybind_data_creg.hpp
src/framework/results/data/mixins/pybind_data_cvector.hpp
src/framework/results/data/mixins/pybind_data_json.hpp
src/framework/results/data/mixins/pybind_data_mps.hpp
src/framework/results/data/mixins/pybind_data_rdict.hpp
src/framework/results/data/mixins/pybind_data_rvalue.hpp
src/framework/results/data/mixins/pybind_data_rvector.hpp
src/framework/results/data/pybind_data.hpp
src/framework/results/data/pybind_metadata.hpp
src/framework/results/data/subtypes/accum_data.hpp
src/framework/results/data/subtypes/average_data.hpp
src/framework/results/data/subtypes/data_map.hpp
src/framework/results/data/subtypes/list_data.hpp
src/framework/results/data/subtypes/pybind_data_map.hpp
src/framework/results/data/subtypes/pybind_subtypes.hpp
src/framework/results/data/subtypes/single_data.hpp
src/framework/results/experiment_result.hpp
src/framework/results/legacy/average_data.hpp
src/framework/results/legacy/average_snapshot.hpp
src/framework/results/legacy/data_container.hpp
src/framework/results/legacy/pershot_data.hpp
src/framework/results/legacy/pershot_snapshot.hpp
src/framework/results/legacy/pybind_data.hpp
src/framework/results/legacy/snapshot_data.hpp
src/framework/results/pybind_result.hpp
src/framework/results/result.hpp
src/framework/rng.hpp
src/framework/stl_ostream.hpp
src/framework/types.hpp
src/framework/utils.hpp
src/misc/clang_omp_symbols.hpp
src/misc/common_macros.hpp
src/misc/gcc_omp_symbols.hpp
src/misc/hacks.hpp
src/misc/warnings.hpp
src/misc/wrap_thrust.hpp
src/noise/noise_model.hpp
src/noise/quantum_error.hpp
src/noise/readout_error.hpp
src/open_pulse/CMakeLists.txt
src/open_pulse/eval_hamiltonian.hpp
src/open_pulse/iterators.hpp
src/open_pulse/log.hpp
src/open_pulse/numeric_integrator.cpp
src/open_pulse/numeric_integrator.hpp
src/open_pulse/ordered_map.hpp
src/open_pulse/pulse_utils.cpp
src/open_pulse/pulse_utils.hpp
src/open_pulse/pulse_utils_bindings.cpp
src/open_pulse/python_to_cpp.hpp
src/open_pulse/test_python_to_cpp.cpp
src/open_pulse/test_python_to_cpp.hpp
src/open_pulse/types.hpp
src/open_pulse/zspmv.cpp
src/open_pulse/zspmv.hpp
src/simulators/density_matrix/densitymatrix.hpp
src/simulators/density_matrix/densitymatrix_state.hpp
src/simulators/density_matrix/densitymatrix_thrust.hpp
src/simulators/extended_stabilizer/ch_runner.hpp
src/simulators/extended_stabilizer/chlib/chstabilizer.hpp
src/simulators/extended_stabilizer/chlib/core.hpp
src/simulators/extended_stabilizer/extended_stabilizer_state.hpp
src/simulators/extended_stabilizer/gates.hpp
src/simulators/matrix_product_state/matrix_product_state.hpp
src/simulators/matrix_product_state/matrix_product_state_internal.cpp
src/simulators/matrix_product_state/matrix_product_state_internal.hpp
src/simulators/matrix_product_state/matrix_product_state_tensor.hpp
src/simulators/matrix_product_state/svd.cpp
src/simulators/matrix_product_state/svd.hpp
src/simulators/stabilizer/binary_vector.hpp
src/simulators/stabilizer/clifford.hpp
src/simulators/stabilizer/pauli.hpp
src/simulators/stabilizer/stabilizer_state.hpp
src/simulators/state.hpp
src/simulators/state_chunk.hpp
src/simulators/statevector/chunk/chunk.hpp
src/simulators/statevector/chunk/chunk_container.hpp
src/simulators/statevector/chunk/chunk_manager.hpp
src/simulators/statevector/chunk/cuda_kernels.hpp
src/simulators/statevector/chunk/device_chunk_container.hpp
src/simulators/statevector/chunk/host_chunk_container.hpp
src/simulators/statevector/indexes.hpp
src/simulators/statevector/qubitvector.hpp
src/simulators/statevector/qubitvector_thrust.hpp
src/simulators/statevector/qv_avx2.cpp
src/simulators/statevector/qv_avx2.hpp
src/simulators/statevector/statevector_state.hpp
src/simulators/statevector/transformer.hpp
src/simulators/statevector/transformer_avx2.hpp
src/simulators/superoperator/superoperator.hpp
src/simulators/superoperator/superoperator_state.hpp
src/simulators/superoperator/superoperator_thrust.hpp
src/simulators/unitary/unitary_state.hpp
src/simulators/unitary/unitarymatrix.hpp
src/simulators/unitary/unitarymatrix_thrust.hpp
src/third-party/win32/lib/openblas.7z
src/third-party/win64/lib/openblas.7z
src/transpile/basic_opts.hpp
src/transpile/cacheblocking.hpp
src/transpile/circuitopt.hpp
src/transpile/fusion.hpp
```

### Steps to reproduce the problem
regular installation

### What is the expected behavior?
no such files shuld be installed

### Suggested solutions
fix it

**Comment by mtreinish** [comment] 2022-08-08 23:16
I think that this is a duplicate of: https://github.com/Qiskit/qiskit-aer/issues/1457

**Comment by yurivict** [comment] 2022-08-09 00:14
This is quite a damaging bug, it pretty much prevents packaging and distribution.
Therefore it should have the highest priority.

**Comment by mtreinish** [comment] 2022-08-09 16:58
I don't view it quite as severe, especially from a packaging perspective it's very easy to filter these as part of your packaging spec file (whichever format you're using). That being said the reason this wasn't an easy fix as it's a bug in the upstream scikit-build which is used to manage the C++ of qiskit-aer (see my comment on this: https://github.com/Qiskit/qiskit-aer/issues/1457#issuecomment-1068345930 ). We're kind of stuck until its fixed in scikit-build as we need to include the c++ src in the sdist with the manifest file to ensure it's available for building from source. But doing that causes scikit-build to inject it into built/installed packages incorrectly.

**Closed** 2022-08-09 18:16 UTC
Labels: bug
