### ISSUE TITLE
dt isn't getting pulled into the openpulse solver correctly

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-aer#449] opened 2019-11-15 01:26 UTC
The `dt` parameters doesn't seem to be getting used by the solver correctly. In the example notebook it's changed it should affect the Rabi frequency in a deterministic way and it doesn't seem to be. This could be due to the pulse interpolation (i.e. the look up is not getting divided by dt). 

### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

**Comment by dcmckayibm** [comment] 2019-11-15 01:30
For example, we should be able to set dt=1e-9 and all the frequencies to GHz and this also doesn't seem to work

**Comment by nonhermitian** [comment] 2019-11-17 14:09
This is because the solver was designed to use natural units. This is a standard thing to do in numerics.

**Comment by dcmckayibm** [comment] 2019-11-18 04:15
Right, but since open pulse gives pulses as a list of samples there is a missing time unit (the time between samples) and that time is `dt`.

**Comment by nonhermitian** [comment] 2019-11-18 09:32
It is used here: https://github.com/Qiskit/qiskit-aer/blob/64e987d90e8847f31215bda05dfb6fc40849647e/qiskit/providers/aer/openpulse/qobj/digest.py#L412

to set the width of a pulse in time, and it the computation of the max_time needed in the simulations.

**Comment by dcmckayibm** [comment] 2019-11-18 16:46
Doesn't it need to be in chan_val (eg these lines https://github.com/Qiskit/qiskit-aer/blob/64e987d90e8847f31215bda05dfb6fc40849647e/qiskit/providers/aer/openpulse/cy/channel_value.pyx#L83) to determine which sample to pick?

**Comment by nonhermitian** [comment] 2019-11-18 17:13
I believe `start_time` and `stop_time` are used to determine the index that corresponds to the value of the channel in the discrete list of pulse values.

**Comment by dcmckayibm** [comment] 2019-11-19 05:26
Ok,I see what you're saying, but I was getting some non-intuitive answers by changing `dt`, so it might be good to double check.

**Comment by DanPuzzuoli** [comment] 2019-11-27 15:22
I think I've found the source of the error in `experiment_to_structs`: there are a few places where 'sample time' is being erroneously combined with 'real time' (i.e. `inst['t0']` vs  `inst['t0']*dt`). E.g.
https://github.com/Qiskit/qiskit-aer/blob/8b2cfa59e3006b75fbcd768ce5c3149a4e955c35/qiskit/providers/aer/openpulse/qobj/digest.py#L519-L520
`inst['t0']` is in 'sample time', but `dt*inst['duration']` is in 'real time'.

The issue seems to be fixed if you just replace all appearances of `inst['t0']` with `inst['t0']*dt` in `experiment_to_structs`. Once you do this the Rabi oscillation does seem - at least by eye - to respond appropriately to changing `dt`.

I can make this change, but just wanted to verify: Are all 'time' parameters in `structs` meant to be in 'real time', or are any supposed to be kept in `sample time`? Are you aware of any further places that this could come up (e.g. in `chan_val`, if the simulator has access to any time information other than what is set in `structs`)?

@dcmckayibm, @nonhermitian

**Comment by nonhermitian** [comment] 2019-11-27 16:08
T0 is no longer measured in actual time?

**Comment by DanPuzzuoli** [comment] 2019-11-27 16:40
As far as I am aware `inst['t0']` is coming directly from the start time of a pulse instruction, which is always an `int`.

**Comment by nonhermitian** [comment] 2019-11-27 16:58
I do not recall that being in the spec, but could be wrong.

**Comment by dcmckayibm** [comment] 2019-11-27 22:47
any "times" in the pulse schedules are in terms of `dt`

**Comment by nonhermitian** [comment] 2019-11-27 22:58
Ok then there is the problem.

**Comment by chriseclectic** [comment] 2019-12-08 18:46
Closed by #473

**Closed by chriseclectic** 2019-12-08 18:46 UTC
Labels: PulseSimulator, bug
